version: "3.7"

services:
  api1: # API - Instância 01
    # image: lucaswilliameufrasio/backend-cockfighting-api
    # container paused, has to manually start from:
    # docker-compose exec api1 sh
    # then:
    # /app/backend-cockfighting-api &
    # trying to start directly makes it crash
    build: .
    command: sleep infinity
    environment:
      - PORT=8080
      - DB_HOST=localhost
      - DB_PORT=5432
      - DB_NAME=fight
      - DB_USER=postgres
      - DB_PASSWORD=fight
      - DB_MAX_CONNECTIONS=75
      - NUM_THREADS=20
    depends_on:
      - db
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.4GB'

  api2: # API - Instância 02
    # image: lucaswilliameufrasio/backend-cockfighting-api
    build: .
    command: sleep infinity
    environment:
      - PORT=8081
      - DB_HOST=localhost
      - DB_PORT=5432
      - DB_NAME=fight
      - DB_USER=postgres
      - DB_PASSWORD=fight
      - DB_MAX_CONNECTIONS=75
      - NUM_THREADS=20
    depends_on:
      - db
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.4GB'

  nginx: # Load Balancer
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: '0.4GB'

  db:
    image: postgres:15
    hostname: db
    container_name: backend-cockfighting-database
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    environment:
      - POSTGRES_PASSWORD=fight
      - POSTGRES_DB=fight
    volumes:
      - ./docker/database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./docker/database/postgresql.conf:/etc/postgresql/postgresql.conf
    network_mode: host
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '0.85'
          memory: '1.8GB'
